### ISSUE TITLE
Layout: Header bar considerations

### ISSUE THREAD

**Issue by alecpl** [roundcube/elastic#1]
![header](https://cloud.githubusercontent.com/assets/546788/21956465/b5b46b2c-da81-11e6-8f5b-75d6cb89f529.png)

Let's discuss the proposed header line. Do we really need it?
1. I would anyway not display the header bar on small screens. 
2. Logo - I think it's not really needed because we can put branding in watermark.html and logon screen.
3. Logout button - can be put in the left-menu.
4. Compose button - can be put in the left-menu.
5. Search - we don't really have global search feature and I'd prefer to put search form in the list header (as it is implemented in elastic now).
6. Username/photo - that actually (together with "About" and "Get Support" links) is the only valid reason for the header bar. Note we do not support user logo at the moment.

So, what do you think? Could anyone propose a better design of the header bar? Other ideas?

**Comment by johnajackson-zz** [comment]
I don't think it's needed. If there's no global search, then I think it would be better to drop the search to the same level as your inbox/contacts. I don't see a need to display the logo, because as you said, users will see it upon logging in; no need to waste space reinforcing the brand once the user is already in the app. We can play around with the avatar, but I'm pretty sure we can easily find a place for it.

**Comment by alecpl** [comment]
Ok, but we'd need to do something with Username and About + Get Support links. We could put links in the menu, but where to put the username? In a phone-mode it could be in the menu too, but on desktop where? Or maybe we should have a small-height header bar on top as in the Larry skin?

**Comment by johnajackson-zz** [comment]
The username/email address could be listed on the sidebar. For example: https://dribbble.com/shots/2637330-Email-Interface-Open-Source/attachments/528211

**Comment by alecpl** [comment]
That's an option. It will not be always visible in tablet mode where the sidebar is hidden, but that might not be a big issue. @thomascube what's your opinion? Thinking also about extendability, maybe the additional small-height header bar wouldn't be so bad idea. It would give some place to put additional "links". On the other hand it would be hidden on phones and not-so-wide on tablets. I have no strong opinion about that.

**Comment by johnajackson-zz** [comment]
My opinion would be formed based moreso on the value of an additional header. Is there value in it other than the fact that it would display the user's username/email address?

**Comment by alecpl** [comment]
@johnajackson only for username it would make no sense, but we could put there the About and Get support links and provide additional space for plugins. So, question is, can we put these somewhere else?

**Comment by pom2ter** [comment]
Heres my take
Logo is not really needed after the login screen.
Search should be visible in the 'main' view since its an important feature.
About, support and other links could appear in a sidebar/menu
Username/email could also appear in a sidebar/menu
Header bar should be the name of the current view/folder/message

**Comment by johnajackson-zz** [comment]
I agree with pom2ter, we can put those extra links in the sidebar instead of creating a completely separate section for them.
