### ISSUE TITLE
Iframes with forms do not scroll in Android

### ISSUE THREAD

**Issue by alecpl** [roundcube/elastic#117]
On Android (tested version 7) iframes with formcontainer/formcontent do not scroll. E.g. contact edit frame, Preferences frames.

**Comment by alecpl** [comment]
Hmm... False alarm. Today I tested two different devices, including the one tested before, and it works. Maybe some caching issue.

**Comment by johndoh** [comment]
I saw this too. The issue is this line: https://github.com/roundcube/elastic/blob/master/styles/widgets/forms.less#L340 and this https://github.com/roundcube/roundcubemail/commit/5dbe1f2a5e7e63e5d44c2e025554675affdf3c32 makes phones not tablets any more, so the issue goes away. not sure what happens on tablets that run android.

**Comment by alecpl** [comment]
Thanks for the info. Indeed, it's still broken on Android tablets. I'll work on this.

**Comment by alecpl** [comment]
Should be fixed now, but it is a pain in the ass. Still some elements do not display scrollbar on mobile/tablets where it usually appears on desktop. Any help appreciated, I'm tired of this for now.
