### ISSUE TITLE
Please provide the compiled CSS files

### ISSUE THREAD

**Issue by fodorgeza** [roundcube/elastic#139]
I just tried to set up yesterday this package but received a lot of errors compiling the .less files. It was only 5-6 files that could been compiled without errors. I was using http://winless.org/ Windows compiler.

I think - and maybe others also do - that it would be a nice service if you could provide the up to date CSS files as well.

**Comment by alecpl** [comment]
When we're ready the repo will be merged into Roundcube repo, then we'll do Roundcube Releases as usual which will contain compiled code. Other than that we'll not provide compiled css.

I think your problem is that you compile every file separately. This will not work. You have to compile styles.less file only (and two others described in README.md file).
