### ISSUE TITLE
Design contact preview and edit form

### ISSUE THREAD

**Issue by alecpl** [roundcube/elastic#29]
Here's a screenshot from Larry, to make the description simpler:
![contact-edit](https://cloud.githubusercontent.com/assets/546788/24856996/e401263e-1de6-11e7-892e-a2c1400e4803.png)
I think this is not very pretty, we could do better. Let's see what we have here:
1. Contact photo with Add button. I think we could put the link/button into the photo image box, not below. When the image is set it would be Edit button. I'm not sure we really need Delete.
2. This selector allows as to add more fields like Organization, Prefix, Job title, etc.
3. Tabs. The form is too big, so we'd probably stay with tabs. We need something different for mobile.
4. Another "add field" select that gives possibility to add more fields like Homepage, but also additional Email, Address and Phone.
5. The form body itself could be prettier, better aligned, etc. I'm not sure we can make it more functional. Probably applying some Bootstrap form style will do the job.
The whole layout needs a graphic designer touch.

**Comment by johnajackson-zz** [comment]
1. I agree with placing the "add photo" action within the default photo. As a new user, I would tap the default photo to change/upload my own. As a returning user, I would tap the current photo to change/upload a different one.

2. Are these fields predetermined or is the user able to create custom fields?

3. We can experiment with this to determine the best route to take. Are my edits saved any time that I change to a different tab or do I need to click the "Save" button first?

4. Refer to second question.

5. I can design a high fidelity version so that we can better understand our options.

**Additional Comments:**
While placeholder text is cleaner, it can hinder user experience because the text disappears when the user clicks into the field. If you look at Material Design (or other forms in general), the input heading is always present, but moves or becomes smaller when the field is active.

**Comment by alecpl** [comment]
2. No, user cannot create custom fields. The list is constant.
3. All changes are saved when you click Save button.
4. Here the list of fields is also constant. Note that we have already a request to support custom fields, but this is not implemented yet. I'd probably put such functionality into a separate tab.

**Comment by gnadelwartz** [comment]
I propose to get rid of the #4 fields dropdown completely.
Instead show all categories haeder (currently 5) and add a plus sign to add a new entry
![bildschirmfoto vom 2017-05-02 14-31-17](https://cloud.githubusercontent.com/assets/4593242/25618257/930e2788-2f46-11e7-9baf-c627a82d5076.png)

I know this may not so easy without breaking existing themes because fields and dropdowns are created by code, not skin, but It looks more constistent to me

**Comment by alecpl** [comment]
@gnadelwartz's proposal for [4] sounds good. Note that in Personal Information tab we have also the "Add field" selector with options: Maiden name, Anniversary, Manager, Assistant, Spouse. So, not so much and it might make sense to display all these fields by default. But... some addressbook plugins add more, e.g. Kolab adds Profession, Children, Free-busy URL, PGP public key, S/MIME public key there.

**Comment by alecpl** [comment]
I consider this mostly done. https://kolabian.wordpress.com/2017/10/23/elastic-contact-data-presentation/
