### ISSUE TITLE
Css issues in Internet Explorer

### ISSUE THREAD

**Issue by alecpl** [roundcube/elastic#30]
I tested IE11 (but we should also test IE10) and found some issues:
1. Toolbar icons are misaligned
2. Recipient boxes in recipient input have "delete" button on left and without cursor:pointer.
3. Forms (e.g. in Preferences > User interface) are broken.
4. Search bar animation is not how it should be.
5. Buttons (of <button> elements) icon is misaligned.

**Comment by pom2ter** [comment]
i can confirm that there are several bugs in IE10, mostly related to display:flex that IE10 doesnt recognize. Its mostly fixed by using display:-ms-flexbox. Also -ms-flex instead of flex-grow. Anything else with flex needs to have the -ms- prefix for IE10.

There are still small bugs here and there but the above fixes about 90% of issues.

**Comment by alecpl** [comment]
I fixed the rest of the issues. So, now we have only the flexbox issues in IE10. Thanks @pom2ter for looking into that. I suppose, we'll fix this with a mixin for set of flex properties that set standard and non-standard props. For now we'll support only IE10. I see Bootstrap sets also some -webkit properties in flexbox layout. I'm not sure yet we'll need them.

**Comment by alecpl** [comment]
IE10 worldwide usage is 1% or less. Much less that IE11. I think we can just not support IE10.
