### ISSUE TITLE
disabling plugins for mobile view

### ISSUE THREAD

**Issue by kwiatek6324** [roundcube/elastic#49]
This is feature request for roundcube dev-elastic branch but is based on elastic requirements.

I think that very good idea is to add possibility to disable some plugins for mobile/tablet view,
because of problems with mobile view in this plugins.

For now, almost all available plugins working only in web view, and they will need some time
to change layout to elastic from larry/classic.

Disabling them on mobile view should be nice feature.

Regards

**Comment by alecpl** [comment]
That would depend on a plugin, but mobile view is not the only problem. Plugin features might not work also with the desktop view in Elastic. It just because it's a completely different skin.

So, what we would need is generally a way to disable a specific plugin when Elastic is in use. That however, still might be tricky and depend on how the plugin is initialized.

**Comment by kwiatek6324** [comment]
Maybe the best way should be adding new configuration directive

disabled_plugins_[dektop|tablet|mobile] ?

I think that preparing desktop view for existing modules will
take  less time than mobile versions, and on beginning using elastic skin
modules will work on desktop view only after accomodation.

Regards
AK

**Comment by alecpl** [comment]
Elastic supports special `data-hidden` attribute that can be used to hide elements on mobile. See https://github.com/roundcube/roundcubemail/blob/master/skins/elastic/README.md
