### ISSUE TITLE
Filter and Search

### ISSUE THREAD

**Issue by mbohlender** [roundcube/elastic#90]
It is currently possible to filter a list of emails or to search for emails.
Most users don't understand the difference.

In Kube, we decided to not offer "filter" at all because with a powerful enough search every filter usecase is basically covered when search just gives you the same result.

**Comment by alecpl** [comment]
We used to have a select available for the user without a need for going through many clicks in search UI. It's because e.g. "filtering" for unread is quite a common task. In Elastic it is hidden behind an icon (one extra click). I agree it's not perfect, but I'm not sure if moving filter to search is better.

**Comment by alecpl** [comment]
Done.
