### ISSUE TITLE
Sidebar visualization confusing

### ISSUE THREAD

**Issue by mbohlender** [roundcube/elastic#97]
Current state:
active is white, inactive is grey, compose is blue.
sidebar content changes, depending on what is selected. (refresh is shown / composer is not shown)

This is inconsistent with the rest of the application where selected is always blue and disabled is grey.
sidebar content changes are a bad idea. The composer is still there, if you select it. so do not hide it. 

Suggestion:
Never change the content of the sidebar.
Highlight the active app (mail / calendar / composer ) with the (blue) highlight color.
all other apps should be white.

If you want to highlight the primary action (composer), use green instead.

We need to find a better place for refresh.

**Comment by alecpl** [comment]
Yes, I was already thinking about moving Refresh to the list widget footer. It belongs more to the messages list than to the rest, I agree, but it need to be noted that refreshing also updates counters on folders list.

As for green Compose button. I do not agree. We use green to indicate success-action or selection-state (only in one place, so this one may change). We use blue for main-buttons (forms, dialogs), so I think it's fine for Compose too. Until we modify other places to use more green color, I don't really see a point.

Sidebar menu has no disabled items, so is a little bit different that other toolbars. Also, it was designed this way by a designer, not me. Because of that it uses grey color for default and white for selected state. But I think we could try white/blue instead of gray/white for sidebar.

**Comment by alecpl** [comment]
Refactored, I consider this fixed. Though, a designer could look at it again.
